### ISSUE TITLE
Error in Theorem 20 - Chapter 7 (Auctions)

### ISSUE THREAD

**Issue by nimalg** [UCL-INMA/LINMA2345#40]
There is an error in the statement of Theorem 20  (p.93)  : the seller's strategy is not correct. The correct one would be :   p_s(v_s) = x,  if  v_s   <=  x   and  1,  otherwise 
(like in the slides available on Moodle)

**Comment by blegat** [comment]
Indeed ! Thanks for the notice ;)

**Comment by gauthmug** [comment]
I have just fixed this typo :)

**Comment by blegat** [comment]
@gauthmug It is already fixed in 8a807875f33b2cf11ee74d3dd2bccd95b191795e ;)

**Comment by gauthmug** [comment]
Not completely because the 0 still had to be changed to 1, right?
