### ISSUE TITLE
APE8 exercise 1 solution typo

### ISSUE THREAD

**Issue by dellafailleh** [UCL-INMA/LINMA2345#54]
At the end of the solution of exercise 1 APE8 to answer the part b, it is writen: 

On the other hand, the point that **maximizes** the expected sum of payoffs
of the two players is point C.

C is the point that  **minimizes** the expected sum of payoffs
of the two players.

The solution is well writen otherwise ;)

**Comment by blegat** [comment]
cc @gauthmug

**Comment by gauthmug** [comment]
I agree! This is fixed in  https://github.com/UCL-INMA/LINMA2345/pull/53/commits/545accee45ccb17e5f36f39adaa85a0607029ec6. Thanks ! :)
